---

version: "3.7"

services:
  app:
    working_dir: /app
    build: .
    command: bundle exec puma -C config/puma.rb
    ports:
      - 80:3000
    volumes:
      - .:/app
      #- ~/bundle-install:/app/vendor/bundle
